# Generated by Django 4.1.1 on 2022-09-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_email', models.EmailField(max_length=254, unique=True)),
                ('c_phone', models.IntegerField(unique=True)),
                ('c_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gross_cost', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('Online', 'Online')], max_length=50)),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('invoice_date', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GST',
            fields=[
                ('gst_id', models.IntegerField(primary_key=True, serialize=False)),
                ('igst', models.IntegerField()),
                ('hsn_code', models.IntegerField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=100)),
                ('p_img', models.ImageField(upload_to='product')),
                ('p_price', models.FloatField()),
                ('product_stock', models.FloatField()),
                ('unit', models.CharField(max_length=100)),
                ('reorder_level', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.discount')),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gst')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.FloatField(default=200000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(max_length=100)),
                ('v_phone', models.IntegerField(unique=True)),
                ('v_email', models.EmailField(max_length=254, unique=True)),
                ('v_address', models.CharField(blank=True, max_length=255, null=True)),
                ('v_gst_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('v_invoice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('purchaseorder', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vendor'),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('customerinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customerinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.discount'),
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('bs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('light_bill', models.FloatField()),
                ('emp_salary', models.FloatField()),
                ('monthly_rent', models.FloatField()),
                ('miscellaneous', models.FloatField()),
                ('bs_date', models.DateField()),
                ('customerinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customerinvoice')),
                ('vendorinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.vendorinvoice')),
            ],
        ),
    ]
